### ISSUE TITLE
OSX equivalent 

### ISSUE THREAD

**Issue by machocam** [nbeaver/why-linux-is-better#1]
Apologies for adding this as an issue. 

Do you have the expertise for building a similar document comoaris OSX to Linux?

**Comment by FormerlyChucks** [comment]
I think this would be a great idea. I'd contribute also.

**Comment by nbeaver** [comment]
@machocam @Mr-Steal-Your-Script  I haven't used OS X for about ten years, and have never owned a Mac. However, I would certainly encourage you to do a write-up of your own!
