### ISSUE TITLE
Patch Guard 3 Equivalent?

### ISSUE THREAD

**Issue by ahmedalnuaimi** [nbeaver/why-linux-is-better#2]
For some reason I never see people making a comparison to Patch Guard 3. What do you think of this feature?

**Comment by nbeaver** [comment]
@ahmedalnuaimi I'm afraid I don't know what that is, sorry!

**Comment by ahmedalnuaimi** [comment]
well this is very important for any Linux comparison. You can't claim that Linux is better if you know nothing about Patch Guard 3!!

**Comment by surendrajat** [comment]
I don't know about this either but I can still claim that Linux is better (at least for me and most of the people I know).

**Comment by ahmedalnuaimi** [comment]
Well I don't know about the advantages of Linux and I can still claim that Windows is better
Does this seem to be a valid argument?
"I don't know what is it by I'm sure that it's good"!!
or maybe, just maybe, you could use Google to find some articles about that? or do you want me to explain it to you here?

**Comment by surendrajat** [comment]
So this is a **magical thing** that somehow removes **ads** from the start menu, disables **Cortana** and all the **data collection**, removes all the **telemetry**, fixes the **registry** nightmare, makes windows less **resource hungry**, makes it **opensource**, stops the **forced updates**? If no, I'm not interested. Thank you.
And yes. You can still claim that Windows is better. You can claim anything actually. And that's what I'm saying. It's also civil to take arguments against your claim and being asked for proof but once again, you can claim anything.

**Comment by ahmedalnuaimi** [comment]
it is perfectly civil to try to read and understand the argument of the otherside. Patch Gward 3 is a deal breaker for Desktop Users. All the points you mentioned earlier are easily disabled by some small tweaks. can you tell me which Linux tweak can add something like Patch Guard 3?
Let me explain what Patch Guard 3 for you since you insist on your ignorance: it prevents kernel patching to hook to important kernel routine. Not even ring0 apps can do that due to periodical, random checks done by the kernel. These checks a protected by "obscurity" and they are routinely updated. This is the MAIN reason why there are no rootkits in recent Windows version.
Now that you learned something, tell me how do Linux distributions protect from rootkits?
