### ISSUE TITLE
The package manager section should mention Microsoft Store

### ISSUE THREAD

**Issue by AnsisMalins** [nbeaver/why-linux-is-better#5]

**Comment by nbeaver** [comment]
@AnsisMalins I'm guessing this part of the crowd coming over from [the Hacker News post](https://news.ycombinator.com/item?id=25104828). At the time (2014), the Microsoft Store was quite new and I still don't know enough about it to comment. Do people actually use it as a package manager like they would use `apt` or `rpm`?

**Comment by AnsisMalins** [comment]
Secondhand Hacker News, I guess. No, people don't use it. I don't, and I don't know anyone who does. And I too know nothing about it. In which case a mention of "there's also Microsoft Store, but nobody uses it, and I know nothing about it" would suffice.
